---
- hosts: all
  #roles:
  become: true  # use sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: apt update
      apt:
        update_cache: yes
    - name: apt upgrade
      apt:
        name: "*"
        state: latest
    - name: apt dist-upgrade
      apt:
        upgrade: dist
  tasks:
    - name: edit /etc/default/grub
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"$'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash consoleblank=60 mitigations=off"'
        backrefs: yes

    - name: Print a variable
      ansible.builtin.debug:
        var: with_gui

    - name: Update Grub
      shell: /usr/sbin/update-grub

    - name: edit /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '(\s+)errors(.*)?$'
        replace: '\1noatime,errors\2'
        validate: '/bin/mount -f -T %s'

    - name: edit /etc/sysctl.conf vm.swappiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '10'
    - name: edit /etc/sysctl.conf vm.dirty_background_ratio
      ansible.posix.sysctl:
        name: vm.dirty_background_ratio
        value: '5'
    - name: edit /etc/sysctl.conf vm.dirty_ratio
      ansible.posix.sysctl:
        name: vm.dirty_ratio
        value: '5'
    - name: edit /etc/sysctl.conf fs.inotify.max_user_watches
      ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: '524288'
    - name: edit /etc/sysctl.conf net.ipv6.conf.all.disable_ipv6
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: '1'
    - name: edit /etc/sysctl.conf net.ipv6.conf.default.disable_ipv6
      ansible.posix.sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: '1'        
        reload: yes

    - name: apt-key - chrome
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
    - name: apt-repo - chrome
      apt_repository:
        repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome

    - name: apt-key - Terraform
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
    - name: apt-repo - Terraform
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com jammy main
        filename: terraform

    - name: apt-key - Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        filename: docker

    - name: apt-repo - Python
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: apt-repo - ULauncher
      apt_repository:
        repo: ppa:agornostal/ulauncher

    - name: apt-repo - Ansible
      apt_repository:
        repo: ppa:ansible/ansible

    - name: apt-repo - OpenJDK
      apt_repository:
        repo: ppa:openjdk-r/ppa

    - name: apt-key - NodeJS
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - name: Add NodeJS Repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_18.x jammy main
        filename: nodejs

    - name: APT Install (Non-GUI)
      apt:
        pkg:
        - mdadm
        - git
        - gnupg
        - gcc
        - g++
        - curl
        - gnupg
        - software-properties-common
        - make
        - python3.11
        - net-tools
        - sshpass
        - stow
        - terraform
        - ansible
        - openjdk-11-jdk
        - openjdk-17-jdk
        - nodejs
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

    - name: APT Install (GUI)
      apt:
        pkg:
        - vlc
        - ibus-table-cangjie3
        - ibus-table-quick
        - terminator
        - gparted
        - pinta
        - filezilla
        - google-chrome-stable
        - ulauncher
        - gnome-tweaks
      when: with_gui == true

    - name: Autoremove
      apt:
        autoremove: yes

    - name: Snap Classic
      snap:
        name:
          - intellij-idea-community
          - pycharm-community
          - sublime-text
          - sublime-merge
          - code
          - slack
          - google-cloud-sdk 
          - aws-cli
        classic: yes
      when: with_gui == true

    - name: Snap
      snap: 
        name:
          - dbeaver-ce
          - discord
          - zoom-client
          - postman
          - teams-for-linux
          - telegram-desktop
      when: with_gui == true

    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker

    - name: adding existing user '{{ ansible_user }}' to group docker
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes

