- hosts: "servers"
  become: true  # use sudo
  tasks:
  - name: Apt Update
    apt:
      update_cache: yes
      upgrade: dist
  - name: Autoremove
    apt:
      autoremove: yes
      autoclean: yes
  - name: Reboot if needed
    reboot:
      msg: "Reboot initiated by Ansible for a package upgrade"
      pre_reboot_delay: 30
      post_reboot_delay: 60
      reboot_timeout: 600
    when: 
      inventory_hostname not in groups.no_reboot
  - name: Print a variable
    ansible.builtin.debug:
      msg: Maintenance complete!
    # tags: hello

  # MySQL Backup  
  # - name: Backup MySQL
  #   import_playbook: playbooks/backup_mysql.yml
    # tags: mysql

  # PostgresSQL Backup
  # - name: Backup PostgreSQL
    # import_playbook: playbooks/backup_postgresql.yml
    # tags: postgresql

  # Folder Backup
  # - name: Backup Files
    # import_playbook: playbooks/backup_postgresql.yml