---
- name: Run install tasks
  ansible.builtin.include_tasks: install.yml
  when: common_install_enabled | bool
  tags:
    - packages

- name: Run maintenance tasks
  ansible.builtin.include_tasks: maintenance.yml
  when: common_maintenance_enabled | bool
  tags:
    - maintenance

- name: Run Docker Update Tasks
  ansible.builtin.include_tasks: docker_update.yml
  when: common_docker_update_enabled | bool
  tags:
    - docker_update
