- hosts: postgresql
  tasks:
  - name: Create variables
    set_fact:
      filename: "{{ ansible_date_time.date | replace('-','') }}"

  - name: Check Python PostgreSQL
    pip:
      name: "{{ item }}"
      executable: pip
      state: present
    with_items:
      - psycopg2

  - name: Backup PostgreSQL
    # mysql_db: state=dump name=all target=/tmp/{{ inventory_hostname }}.sql
    postgresql_db:
      name: "{{ item }}"
      target: /tmp/{{ filename }}_{{ item }}.sql
      state: dump
      login_user: postgres
      login_password: "{{ postgresql_password }}"
      login_host: localhost
    with_items:
    - clicktrade
    - nocodb

  - name: Tar GZIP the SQL
    community.general.archive:
      path: /tmp/{{ filename }}*.sql
      dest: /tmp/{{ filename }}_pg.tar.gz
      format: gz
      force_archive: true

  - name: Fetch file from Remote to local
    fetch: src=/tmp/{{ filename }}_pg.tar.gz dest=~/{{ filename }}_pg.tar.gz flat=yes

  - name: Remove file 
    ansible.builtin.shell: |
      rm -rf /tmp/{{ filename }}*.sql
      rm -rf /tmp/{{ filename }}_pg.tar.gz

  # DON'T USE ansible.builtin.file to remove file, it doesn't work

  # - name: Remove file 
  #   ansible.builtin.file:
  #     path: "{{ item }}"
  #     state: absent
  #   with_fileglob: 
  #   - "/tmp/*.sql"