- hosts: mysql
  tasks:
  - name: Create variables
    set_fact:
      filename: "{{ ansible_date_time.date | replace('-','') }}"

  - name: Check Python MySQL
    pip:
      name: "{{ item }}"
      executable: pip
      state: present
    with_items:
      - PyMySQL

  - name: Backup MySQL
    # mysql_db: state=dump name=all target=/tmp/{{ inventory_hostname }}.sql
    mysql_db: state=dump name={{ item }} target=/tmp/{{ filename }}_{{ item }}.sql
    with_items:
    - wordpress
    - phpmyadmin

  - name: Tar GZIP the SQL
    community.general.archive:
      path: /tmp/{{ filename }}*.sql
      dest: /tmp/{{ filename }}_mysql.tar.gz
      format: gz
      force_archive: true
  
  - name: Fetch file from Remote to local
    fetch: src=/tmp/{{ filename }}_mysql.tar.gz dest=~/{{ filename }}_mysql.tar.gz flat=yes

  - name: Remove file 
    ansible.builtin.shell: |
      rm -rf /tmp/{{ filename }}*.sql
      rm -rf /tmp/{{ filename }}_mysql.tar.gz

  # DON'T USE ansible.builtin.file to remove file, it doesn't work

  # - name: Remove file 
  #   ansible.builtin.file:
  #     path: "{{ item }}"
  #     state: absent
  #   with_fileglob: 
  #   - "/tmp/*.sql"